### ISSUE TITLE
Action fails with: The operation was canceled.

### ISSUE THREAD

**Issue by AdamBien** [graalvm/setup-graalvm#35]
The following action:

```
name: eras3r native build
on: [push]
jobs:
    build:
      name: native ${{ matrix.os }} build
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - uses: graalvm/setup-graalvm@v1
          with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            native-image-job-reports: 'true'
        - name: environment check
          run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
        - name: maven build
          run: eras3r/mvn package
        - name: native build
          run: eras3r/native-image -jar target/eras3r.jar
        - name: upload unix binaries
          if: ${{matrix.os != 'windows-latest'}}
          uses: actions/upload-artifact@v3
          with:
            name: eras3r-${{ matrix.os }}
            path: eras3r/target/eras3r-runner
            if-no-files-found: error
        - name: upload windows binary
          if: ${{matrix.os == 'windows-latest'}}
          uses: actions/upload-artifact@v3
          with:
            name: eras3r-${{ matrix.os }}
            path: eras3r/target/eras3r-runner.exe
            if-no-files-found: error

```

fails with:

##[error]The operation was canceled.

Log:

2023-03-20T02:19:26.4036567Z Requested labels: macos-latest

2023-03-20T02:19:42.5425790Z ##[debug]0
2023-03-20T02:19:42.5426860Z ##[debug]
2023-03-20T02:19:42.5428060Z ::endgroup::
2023-03-20T02:19:42.5428330Z ##[endgroup]
2023-03-20T02:19:42.5429260Z ::group::Disabling automatic garbage collection
2023-03-20T02:19:42.5429640Z ##[group]Disabling automatic garbage collection
2023-03-20T02:19:42.5436190Z [command]/usr/local/bin/git config --local gc.auto 0
2023-03-20T02:19:42.5545490Z ##[debug]0
2023-03-20T02:19:42.5546640Z ##[debug]
2023-03-20T02:19:42.5547650Z ::endgroup::
2023-03-20T02:19:42.5547920Z ##[endgroup]
2023-03-20T02:19:42.5548720Z ::group::Setting up auth
2023-03-20T02:19:42.5549020Z ##[group]Setting up auth
2023-03-20T02:19:42.5560770Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-03-20T02:19:42.5655040Z ##[debug]1
2023-03-20T02:19:42.5655570Z ##[debug]
2023-03-20T02:19:42.5667910Z [command]/usr/local/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-03-20T02:19:42.6968020Z ##[debug]0
2023-03-20T02:19:42.6968520Z ##[debug]
2023-03-20T02:19:42.6977000Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-03-20T02:19:42.7065420Z ##[debug]1
2023-03-20T02:19:42.7065960Z ##[debug]
2023-03-20T02:19:42.7072660Z [command]/usr/local/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-03-20T02:19:42.8257610Z ##[debug]0
2023-03-20T02:19:42.8270810Z ##[debug]
2023-03-20T02:19:42.8278880Z [command]/usr/local/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2023-03-20T02:19:42.8391010Z ##[debug]0
2023-03-20T02:19:42.8422300Z ##[debug]
2023-03-20T02:19:42.8430430Z ::endgroup::
2023-03-20T02:19:42.8430710Z ##[endgroup]
2023-03-20T02:19:42.8436080Z ::group::Fetching the repository
2023-03-20T02:19:42.8436410Z ##[group]Fetching the repository
2023-03-20T02:19:42.8516040Z [command]/usr/local/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +143c105753dc8887e8ac66ac01c3096f2349095c:refs/remotes/origin/main
2023-03-20T02:19:43.2283350Z ##[debug]
2023-03-20T02:19:43.2283800Z ::endgroup::
2023-03-20T02:19:43.2284040Z ##[endgroup]
2023-03-20T02:19:43.2284470Z ::group::Determining the checkout info
2023-03-20T02:19:43.2284790Z ##[group]Determining the checkout info
2023-03-20T02:19:43.2288210Z ::endgroup::
2023-03-20T02:19:43.2288450Z ##[endgroup]
2023-03-20T02:19:43.2289880Z ::group::Checking out the ref
2023-03-20T02:19:43.2290140Z ##[group]Checking out the ref
2023-03-20T02:19:43.2297680Z [command]/usr/local/bin/git checkout --progress --force -B main refs/remotes/origin/main
2023-03-20T02:19:43.2543770Z Switched to a new branch 'main'
2023-03-20T02:19:43.2645480Z branch 'main' set up to track 'origin/main'.
2023-03-20T02:19:43.2718670Z ##[debug]0
2023-03-20T02:19:43.2720280Z ##[debug]branch 'main' set up to track 'origin/main'.
2023-03-20T02:19:43.2720580Z ##[debug]
2023-03-20T02:19:43.2721840Z ::endgroup::
2023-03-20T02:19:43.2722080Z ##[endgroup]
2023-03-20T02:19:43.2723020Z ##[debug]0
2023-03-20T02:19:43.2724250Z ##[debug]commit 143c105753dc8887e8ac66ac01c3096f2349095c
2023-03-20T02:19:43.2724540Z ##[debug]Author: Adam Bien <abien@adam-bien.com>
2023-03-20T02:19:43.2724850Z ##[debug]Date:   Sun Mar 19 21:39:51 2023 +0100
2023-03-20T02:19:43.2725080Z ##[debug]
2023-03-20T02:19:43.2725290Z ##[debug]    switching to latest
2023-03-20T02:19:43.2725530Z ##[debug]
2023-03-20T02:19:43.2726260Z [command]/usr/local/bin/git log -1 --format='%H'
2023-03-20T02:19:43.2806580Z '143c105753dc8887e8ac66ac01c3096f2349095c'
2023-03-20T02:19:43.2813130Z ##[debug]0
2023-03-20T02:19:43.2813850Z ##[debug]'143c105753dc8887e8ac66ac01c3096f2349095c'
2023-03-20T02:19:43.2814090Z ##[debug]
2023-03-20T02:19:43.2822770Z ##[debug]Unsetting HOME override
2023-03-20T02:19:43.2838490Z ::remove-matcher owner=checkout-git::
2023-03-20T02:19:43.2865810Z ##[debug]Removed matchers: 'checkout-git'
2023-03-20T02:19:43.2929490Z ##[debug]Node Action run completed with exit code 0
2023-03-20T02:19:43.3111830Z ##[debug]Save intra-action state isPost = true
2023-03-20T02:19:43.3112270Z ##[debug]Save intra-action state setSafeDirectory = true
2023-03-20T02:19:43.3112680Z ##[debug]Save intra-action state repositoryPath = /Users/runner/work/eras3r/eras3r
2023-03-20T02:19:43.3130900Z ##[debug]Finishing: checkout code
2023-03-20T02:19:43.3150960Z ##[debug]Evaluating condition for step: 'Run graalvm/setup-graalvm@v1'
2023-03-20T02:19:43.3155530Z ##[debug]Evaluating: success()
2023-03-20T02:19:43.3155870Z ##[debug]Evaluating success:
2023-03-20T02:19:43.3156490Z ##[debug]=> true
2023-03-20T02:19:43.3157280Z ##[debug]Result: true
2023-03-20T02:19:43.3158670Z ##[debug]Starting: Run graalvm/setup-graalvm@v1
2023-03-20T02:19:43.3182690Z ##[debug]Register post job cleanup for action: graalvm/setup-graalvm@v1
2023-03-20T02:19:43.3205760Z ##[debug]Loading inputs
2023-03-20T02:19:43.3248940Z ##[debug]Evaluating: secrets.GITHUB_TOKEN
2023-03-20T02:19:43.3249370Z ##[debug]Evaluating Index:
2023-03-20T02:19:43.3249650Z ##[debug]..Evaluating secrets:
2023-03-20T02:19:43.3249960Z ##[debug]..=> Object
2023-03-20T02:19:43.3250220Z ##[debug]..Evaluating String:
2023-03-20T02:19:43.3250480Z ##[debug]..=> 'GITHUB_TOKEN'
2023-03-20T02:19:43.3251350Z ##[debug]=> '***'
2023-03-20T02:19:43.3251840Z ##[debug]Result: '***'
2023-03-20T02:19:43.3268270Z ##[debug]Loading env
2023-03-20T02:19:43.3276950Z ##[group]Run graalvm/setup-graalvm@v1
2023-03-20T02:19:43.3277230Z with:
2023-03-20T02:19:43.3277460Z   version: latest
2023-03-20T02:19:43.3277690Z   java-version: 17
2023-03-20T02:19:43.3277900Z   components: native-image
2023-03-20T02:19:43.3278340Z   github-token: ***
2023-03-20T02:19:43.3278640Z   native-image-job-reports: true
2023-03-20T02:19:43.3278890Z   set-java-home: true
2023-03-20T02:19:43.3279100Z   check-for-updates: true
2023-03-20T02:19:43.3279350Z   native-image-musl: false
2023-03-20T02:19:43.3279630Z   native-image-pr-reports: false
2023-03-20T02:19:43.3279990Z ##[endgroup]
2023-03-20T02:19:43.8767460Z ##[debug]isExplicit: 22.3.1
2023-03-20T02:19:43.8768120Z ##[debug]explicit? true
2023-03-20T02:19:43.8805490Z ##[debug]checking cache: /Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64
2023-03-20T02:19:43.8806570Z ##[debug]not found
2023-03-20T02:19:43.8809240Z ##[debug]Downloading https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-amd64-22.3.1.tar.gz
2023-03-20T02:19:43.8814610Z ##[debug]Destination /Users/runner/work/_temp/a2fcac7d-7bc7-45e9-a26d-e38274692e2c
2023-03-20T02:19:46.3854210Z ##[debug]download complete
2023-03-20T02:19:46.3861300Z ##[debug]Checking tar --version
2023-03-20T02:19:46.4025260Z ##[debug]bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8
2023-03-20T02:19:46.4055920Z [command]/usr/bin/tar xz -v -C /Users/runner/work/_temp/9d382dbd-6612-40c8-b31e-ce96581ca5d5 -f /Users/runner/work/_temp/a2fcac7d-7bc7-45e9-a26d-e38274692e2c
2023-03-20T02:19:46.4115580Z x graalvm-ce-java17-22.3.1/Contents/Info.plist
2023-03-20T02:19:46.4118730Z x graalvm-ce-java17-22.3.1/Contents/Home/release
2023-03-20T02:19:46.4135690Z x graalvm-ce-java17-22.3.1/Contents/Home/THIRD_PARTY_LICENSE.txt
2023-03-20T02:19:46.4139110Z x graalvm-ce-java17-22.3.1/Contents/Home/GRAALVM-README.md
2023-03-20T02:19:46.4143390Z x graalvm-ce-java17-22.3.1/Contents/Home/LICENSE.txt
2023-03-20T02:19:46.4149210Z x graalvm-ce-java17-22.3.1/Contents/Home/tools/insightheap/native-image.properties
2023-03-20T02:19:46.4164640Z x graalvm-ce-java17-22.3.1/Contents/Home/tools/insightheap/insight-heap.jar
(...)
2023-03-20T02:19:51.9463740Z x graalvm-ce-java17-22.3.1/Contents/MacOS/libjli.dylib
2023-03-20T02:19:51.9538970Z Adding graalvm-ce-java17-darwin 22.3.1 to tool-cache ...
2023-03-20T02:19:51.9640850Z ##[debug]Caching tool graalvm-ce-java17-darwin 22.3.1 x64
2023-03-20T02:19:51.9709250Z ##[debug]source dir: /Users/runner/work/_temp/9d382dbd-6612-40c8-b31e-ce96581ca5d5
2023-03-20T02:19:51.9796880Z ##[debug]destination /Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64
2023-03-20T02:19:53.4844150Z ##[debug]finished caching tool
2023-03-20T02:19:53.4849290Z ##[debug]Activating GraalVM located at '/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home'...
2023-03-20T02:19:53.4862120Z [command]/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home/bin/gu --non-interactive install --no-progress native-image
2023-03-20T02:19:56.9925170Z Downloading: Component catalog from www.graalvm.org
2023-03-20T02:19:57.2551280Z Processing Component: Native Image
2023-03-20T02:19:57.2632870Z Downloading: Component native-image: Native Image from github.com
2023-03-20T02:19:59.8372790Z Installing new component: Native Image (org.graalvm.native-image, version 22.3.1)
2023-03-20T02:20:00.7958090Z ##[debug]Re-evaluate condition on job cancellation for step: 'Run graalvm/setup-graalvm@v1'.
2023-03-20T02:20:00.8765270Z ##[debug]GRAALVM_HOME='/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home'
2023-03-20T02:20:00.8766090Z ##[debug]JAVA_HOME='/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home'
2023-03-20T02:20:00.8920680Z ##[error]The operation was canceled.
2023-03-20T02:20:00.8935490Z ##[debug]System.OperationCanceledException: The operation was canceled.
2023-03-20T02:20:00.8935970Z ##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2023-03-20T02:20:00.8936830Z ##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2023-03-20T02:20:00.8938150Z ##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2023-03-20T02:20:00.8939360Z ##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
2023-03-20T02:20:00.8940180Z ##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
2023-03-20T02:20:00.8940740Z ##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
2023-03-20T02:20:00.8941150Z ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2023-03-20T02:20:00.8942820Z ##[debug]Finishing: Run graalvm/setup-graalvm@v1
2023-03-20T02:20:00.9144880Z ##[debug]Evaluating condition for step: 'environment check'
2023-03-20T02:20:00.9146460Z ##[debug]Evaluating: success()
2023-03-20T02:20:00.9146790Z ##[debug]Evaluating success:
2023-03-20T02:20:00.9147550Z ##[debug]=> false
2023-03-20T02:20:00.9148240Z ##[debug]Result: false
2023-03-20T02:20:00.9158050Z ##[debug]Evaluating condition for step: 'maven build'
2023-03-20T02:20:00.9159210Z ##[debug]Evaluating: success()
2023-03-20T02:20:00.9159530Z ##[debug]Evaluating success:
2023-03-20T02:20:00.9159870Z ##[debug]=> false
2023-03-20T02:20:00.9160450Z ##[debug]Result: false
2023-03-20T02:20:00.9169590Z ##[debug]Evaluating condition for step: 'native build'
2023-03-20T02:20:00.9170880Z ##[debug]Evaluating: success()
2023-03-20T02:20:00.9171190Z ##[debug]Evaluating success:
2023-03-20T02:20:00.9171540Z ##[debug]=> false
2023-03-20T02:20:00.9172130Z ##[debug]Result: false
2023-03-20T02:20:00.9183080Z ##[debug]Evaluating condition for step: 'upload unix binaries'
2023-03-20T02:20:00.9224240Z ##[debug]Evaluating: (success() && (matrix.os != 'windows-latest'))
2023-03-20T02:20:00.9224740Z ##[debug]Evaluating And:
2023-03-20T02:20:00.9234040Z ##[debug]..Evaluating success:
2023-03-20T02:20:00.9234510Z ##[debug]..=> false
2023-03-20T02:20:00.9235360Z ##[debug]=> false
2023-03-20T02:20:00.9254680Z ##[debug]Expanded: (false && (matrix['os'] != 'windows-latest'))
2023-03-20T02:20:00.9256800Z ##[debug]Result: false
2023-03-20T02:20:00.9273330Z ##[debug]Evaluating condition for step: 'upload windows binary'
2023-03-20T02:20:00.9277990Z ##[debug]Evaluating: (success() && (matrix.os == 'windows-latest'))
2023-03-20T02:20:00.9278400Z ##[debug]Evaluating And:
2023-03-20T02:20:00.9278700Z ##[debug]..Evaluating success:
2023-03-20T02:20:00.9279120Z ##[debug]..=> false
2023-03-20T02:20:00.9279390Z ##[debug]=> false
2023-03-20T02:20:00.9282000Z ##[debug]Expanded: (false && (matrix['os'] == 'windows-latest'))
2023-03-20T02:20:00.9282610Z ##[debug]Result: false
2023-03-20T02:20:00.9294880Z ##[debug]Evaluating condition for step: 'Post Run graalvm/setup-graalvm@v1'
2023-03-20T02:20:00.9296140Z ##[debug]Evaluating: success()
2023-03-20T02:20:00.9296440Z ##[debug]Evaluating success:
2023-03-20T02:20:00.9296830Z ##[debug]=> false
2023-03-20T02:20:00.9297410Z ##[debug]Result: false
2023-03-20T02:20:00.9664610Z ##[debug]Evaluating condition for step: 'Post checkout code'
2023-03-20T02:20:00.9669500Z ##[debug]Evaluating: always()
2023-03-20T02:20:00.9669830Z ##[debug]Evaluating always:
2023-03-20T02:20:00.9671340Z ##[debug]=> true
2023-03-20T02:20:00.9672080Z ##[debug]Result: true
2023-03-20T02:20:00.9672930Z ##[debug]Starting: Post checkout code
2023-03-20T02:20:00.9725900Z ##[debug]Loading inputs
2023-03-20T02:20:00.9726930Z ##[debug]Evaluating: github.repository
2023-03-20T02:20:00.9727270Z ##[debug]Evaluating Index:
2023-03-20T02:20:00.9727530Z ##[debug]..Evaluating github:
2023-03-20T02:20:00.9727780Z ##[debug]..=> Object
2023-03-20T02:20:00.9728010Z ##[debug]..Evaluating String:
2023-03-20T02:20:00.9728230Z ##[debug]..=> 'repository'
2023-03-20T02:20:00.9728490Z ##[debug]=> 'AdamBien/eras3r'
2023-03-20T02:20:00.9728740Z ##[debug]Result: 'AdamBien/eras3r'
2023-03-20T02:20:00.9730710Z ##[debug]Evaluating: github.token
2023-03-20T02:20:00.9730970Z ##[debug]Evaluating Index:
2023-03-20T02:20:00.9731230Z ##[debug]..Evaluating github:
2023-03-20T02:20:00.9731480Z ##[debug]..=> Object
2023-03-20T02:20:00.9731690Z ##[debug]..Evaluating String:
2023-03-20T02:20:00.9731910Z ##[debug]..=> 'token'
2023-03-20T02:20:00.9732430Z ##[debug]=> '***'
2023-03-20T02:20:00.9732800Z ##[debug]Result: '***'
2023-03-20T02:20:00.9741200Z ##[debug]Loading env
2023-03-20T02:20:00.9750680Z Post job cleanup.
2023-03-20T02:20:01.3422110Z ##[debug]Getting git version
2023-03-20T02:20:01.3430680Z [command]/usr/local/bin/git version
2023-03-20T02:20:01.3609980Z git version 2.39.2
2023-03-20T02:20:01.3671070Z ##[debug]0
2023-03-20T02:20:01.3694760Z ##[debug]git version 2.39.2
2023-03-20T02:20:01.3695010Z ##[debug]
2023-03-20T02:20:01.3696330Z ##[debug]Set git useragent to: git/2.39.2 (github-actions-checkout)
2023-03-20T02:20:01.3773330Z ::add-mask::***
2023-03-20T02:20:01.3878170Z Copying '/Users/runner/.gitconfig' to '/Users/runner/work/_temp/2a337ccb-766f-4179-afe1-47e18a544db3/.gitconfig'
2023-03-20T02:20:01.3948860Z Temporarily overriding HOME='/Users/runner/work/_temp/2a337ccb-766f-4179-afe1-47e18a544db3' before making global git config changes
2023-03-20T02:20:01.3993930Z Adding repository directory to the temporary git global config as a safe directory
2023-03-20T02:20:01.4039040Z [command]/usr/local/bin/git config --global --add safe.directory /Users/runner/work/eras3r/eras3r
2023-03-20T02:20:01.4141040Z ##[debug]0
2023-03-20T02:20:01.4179870Z ##[debug]
2023-03-20T02:20:01.4199460Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-03-20T02:20:01.4214290Z ##[debug]1
2023-03-20T02:20:01.4272140Z ##[debug]
2023-03-20T02:20:01.4297860Z [command]/usr/local/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-03-20T02:20:01.6284360Z ##[debug]0
2023-03-20T02:20:01.6384980Z ##[debug]
2023-03-20T02:20:01.6415200Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-03-20T02:20:01.6427140Z http.https://github.com/.extraheader
2023-03-20T02:20:01.6467600Z ##[debug]0
2023-03-20T02:20:01.6471100Z ##[debug]http.https://github.com/.extraheader
2023-03-20T02:20:01.6471420Z ##[debug]
2023-03-20T02:20:01.6476130Z [command]/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-03-20T02:20:01.6555430Z ##[debug]0
2023-03-20T02:20:01.6570820Z ##[debug]
2023-03-20T02:20:01.6579380Z [command]/usr/local/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-03-20T02:20:01.9086210Z ##[debug]0
2023-03-20T02:20:01.9175170Z ##[debug]
2023-03-20T02:20:01.9292670Z ##[debug]Unsetting HOME override
2023-03-20T02:20:01.9312910Z ##[debug]Node Action run completed with exit code 0
2023-03-20T02:20:01.9317970Z ##[debug]Finishing: Post checkout code
2023-03-20T02:20:01.9519680Z ##[debug]Starting: Complete job
2023-03-20T02:20:01.9522640Z Uploading runner diagnostic logs
2023-03-20T02:20:02.0608070Z ##[debug]Starting diagnostic file upload.
2023-03-20T02:20:02.0608490Z ##[debug]Setting up diagnostic log folders.
2023-03-20T02:20:02.0612610Z ##[debug]Creating diagnostic log files folder.
2023-03-20T02:20:02.0644990Z ##[debug]Copying 1 worker diagnostic logs.
2023-03-20T02:20:02.1079420Z ##[debug]Copying 1 runner diagnostic logs.
2023-03-20T02:20:02.1085890Z ##[debug]Zipping diagnostic files.
2023-03-20T02:20:02.1149100Z ##[debug]Uploading diagnostic metadata file.
2023-03-20T02:20:02.1195630Z ##[debug]Diagnostic file upload complete.
2023-03-20T02:20:02.1196520Z Completed runner diagnostic log upload
2023-03-20T02:20:02.1196860Z Cleaning up orphan processes
2023-03-20T02:20:02.2762360Z ##[debug]Finishing: Complete job
2023-03-20T02:20:02.3015180Z ##[debug]Finishing: native macos-latest build

**Comment by fniephaus** [comment]
Hi Adam, thanks for raising this.

> The operation was canceled.

This error can happen for very different reasons: a timeout, a failing parallel build, a memory leak, etc. Do you have a hunch about what could have caused this in your build? Could you provide a link to the build that failed with the log you attached to your report?

**Comment by AdamBien** [comment]
The build seem to be cancelled during the setup phase:

2023-03-20T02:20:00.7958090Z ##[debug]Re-evaluate condition on job cancellation for step: 'Run graalvm/setup-graalvm@v1'.
2023-03-20T02:20:00.8765270Z ##[debug]GRAALVM_HOME='/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home'
2023-03-20T02:20:00.8766090Z ##[debug]JAVA_HOME='/Users/runner/hostedtoolcache/graalvm-ce-java17-darwin/22.3.1/x64/graalvm-ce-java17-22.3.1/Contents/Home'
2023-03-20T02:20:00.8920680Z ##[error]The operation was canceled.
2023-03-20T02:20:00.8935490Z ##[debug]System.OperationCanceledException: The operation was canceled.
